/* auth types */

export const LOADING = 'LOADING'
export const LOAD_USER = 'LOAD_USER'
export const AUTH_ERROR = 'AUTH_ERROR'
export const REG_SUCCESS = 'REG_SUCCESS'
export const REG_FAIL = 'REG_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const ALL_TYPE_CONNECTIONS = 'ALL_TYPE_CONNECTIONS'
export const CONNECTION_REQUEST_RECEIVED = 'CONNECTION_REQUEST_RECEIVED'
export const SEND_CONNECTION_REQUEST = 'SEND_CONNECTION_REQUEST'
export const CANCEL_CONNECTION_REQUEST = 'CANCEL_CONNECTION_REQUEST'
export const ACCEPT_CONNECTION_REQUEST = 'ACCEPT_CONNECTION_REQUEST'
export const GET_FRIENDS = 'GET_FRIENDS'
export const LOADING_AUTH_CONTENT = 'LOADING_AUTH_CONTENT'

/* messages types */

export const GET_CHATS = 'GET_CHATS'
export const LOADING_CONTENT = 'LOADING_CONTENT'
